[tool.poetry]
name = "ufw"
version = "0.1.0"
description = ""
authors = ["Carson"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sanic = "^22.9.0"
parsedatetime = "^2.6"
apscheduler = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
